/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package projet;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Clement
 */
public class Ouverture extends javax.swing.JFrame {
    

    /**
     * Creates new form Ouverture
     */
    public Ouverture() {
        initComponents();
        //jPanel2.setVisible(false);
        //jLabel1.setText(str);
    }
    
    public Ouverture(String n){
        initComponents();
        name = n;
        labelLoginOp.setText(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jFileChooser2 = new javax.swing.JFileChooser();
        jPanelOuverture = new javax.swing.JPanel();
        labelWelcomeOp = new javax.swing.JLabel();
        panelButtonsOp = new javax.swing.JPanel();
        buttonNewOp = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        buttonOpenOp = new javax.swing.JButton();
        buttonExitOp = new javax.swing.JButton();
        labelLoginOp = new javax.swing.JLabel();
        labelLogoOp = new javax.swing.JLabel();

        jDialog1.setSize(530,350);
        jDialog1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jFileChooser2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser2ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jDialog1Layout = new org.jdesktop.layout.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDialog1Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jFileChooser2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jDialog1Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jFileChooser2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jPanelOuverture.setBackground(new java.awt.Color(204, 204, 204));
        jPanelOuverture.setPreferredSize(new java.awt.Dimension(360, 223));

        labelWelcomeOp.setText("Bienvenue");

        panelButtonsOp.setBackground(new java.awt.Color(204, 204, 204));
        panelButtonsOp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonNewOp.setText("Nouveau projet");
        buttonNewOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewOpActionPerformed(evt);
            }
        });

        buttonOpenOp.setText("Ouvrir un projet existant");
        buttonOpenOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOpenOpActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout panelButtonsOpLayout = new org.jdesktop.layout.GroupLayout(panelButtonsOp);
        panelButtonsOp.setLayout(panelButtonsOpLayout);
        panelButtonsOpLayout.setHorizontalGroup(
            panelButtonsOpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelButtonsOpLayout.createSequentialGroup()
                .addContainerGap()
                .add(panelButtonsOpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jSeparator1)
                    .add(panelButtonsOpLayout.createSequentialGroup()
                        .add(panelButtonsOpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(buttonNewOp)
                            .add(buttonOpenOp))
                        .add(0, 49, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelButtonsOpLayout.setVerticalGroup(
            panelButtonsOpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelButtonsOpLayout.createSequentialGroup()
                .add(7, 7, 7)
                .add(buttonNewOp)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(buttonOpenOp)
                .add(7, 7, 7))
        );

        buttonExitOp.setText("Quitter");
        buttonExitOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitOpActionPerformed(evt);
            }
        });

        labelLoginOp.setText("jLabel3");

        labelLogoOp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projet/LogoWP.png"))); // NOI18N

        org.jdesktop.layout.GroupLayout jPanelOuvertureLayout = new org.jdesktop.layout.GroupLayout(jPanelOuverture);
        jPanelOuverture.setLayout(jPanelOuvertureLayout);
        jPanelOuvertureLayout.setHorizontalGroup(
            jPanelOuvertureLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelOuvertureLayout.createSequentialGroup()
                .add(jPanelOuvertureLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanelOuvertureLayout.createSequentialGroup()
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(buttonExitOp))
                    .add(jPanelOuvertureLayout.createSequentialGroup()
                        .add(84, 84, 84)
                        .add(labelLoginOp)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(labelLogoOp)))
                .add(65, 65, 65))
            .add(jPanelOuvertureLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanelOuvertureLayout.createSequentialGroup()
                    .add(6, 6, 6)
                    .add(jPanelOuvertureLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(panelButtonsOp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(labelWelcomeOp))
                    .add(169, 169, 169)))
        );
        jPanelOuvertureLayout.setVerticalGroup(
            jPanelOuvertureLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelOuvertureLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelOuvertureLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(labelLogoOp)
                    .add(labelLoginOp))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 148, Short.MAX_VALUE)
                .add(buttonExitOp)
                .addContainerGap())
            .add(jPanelOuvertureLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanelOuvertureLayout.createSequentialGroup()
                    .addContainerGap()
                    .add(labelWelcomeOp)
                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 48, Short.MAX_VALUE)
                    .add(panelButtonsOp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(53, 53, 53)))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelOuverture, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 387, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelOuverture, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonExitOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitOpActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_buttonExitOpActionPerformed

    private void buttonOpenOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOpenOpActionPerformed
        // TODO add your handling code here:
        //jDialog1.setVisible(true);
        int returnVal = jFileChooser2.showOpenDialog(jFileChooser2);
 
	if (returnVal == JFileChooser.APPROVE_OPTION) {
            path = jFileChooser2.getSelectedFile().getName();
            System.out.println("OK ! Fichier : " + jFileChooser2.getSelectedFile().getAbsoluteFile());
            try {
                new Webphone(path, name).setVisible(true);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Ouverture.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Ouverture.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.setVisible(false);
        }
        else if (returnVal == JFileChooser.CANCEL_OPTION) {
            System.out.println("CANCEL");
        }			
    }//GEN-LAST:event_buttonOpenOpActionPerformed

    private void jFileChooser2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser2ActionPerformed
        // TODO add your handling code here:
					
			
    }//GEN-LAST:event_jFileChooser2ActionPerformed

    private void buttonNewOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewOpActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        String st = null;
        int r;
        st = JOptionPane.showInputDialog(null, "Indiquez le nom du projet?", st);
        if(st != null) {
            try {
                new Webphone(st, name).setVisible(true);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Ouverture.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Ouverture.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_buttonNewOpActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonExitOp;
    private javax.swing.JButton buttonNewOp;
    private javax.swing.JButton buttonOpenOp;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JPanel jPanelOuverture;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelLoginOp;
    private javax.swing.JLabel labelLogoOp;
    private javax.swing.JLabel labelWelcomeOp;
    private javax.swing.JPanel panelButtonsOp;
    // End of variables declaration//GEN-END:variables

    private String path;
    private String name;
}
